# Generated by Django 3.0 on 2021-06-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210617_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Extended', 'Extended'), ('Returned', 'Returned')], max_length=200, null=True),
        ),
    ]
